title: Jose Flores
description: "Engineering and Project Assistant specializing in SharePoint administration, Power Platform development, and web technologies"
author: Jose Flores
url: "https://yourusername.github.io"  # Replace with your actual URL

# Contact Information Constants
contact:
  email: "JoseTF2396@gmail.com"
  linkedin_url: "https://linkedin.com/in/yourprofile"
  linkedin_handle: "yourprofile"
  github_url: "https://github.com/josetf2396"
  github_handle: "josetf2396"

